name: Express.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install ejs express express-session path jsonwebtoken mysql multer cookie-parser express-rate-limit dotenv

      - name: Run Express.js
        run: node backend/index.js &
        # This runs the Express.js server in the background and redirects console output to a log file.

      - name: Wait for server to start
        run: sleep 5

      - name: Check for console errors
        run: |
          set -e
    
          response_home=$(curl -sS http://localhost:5000/)
          echo "Response from / endpoint:"
          echo "$response_home"


      - name: Stop Express.js
        run: pkill -f "node backend/index.js"
